#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-sslext
Version  : 1.2.0
Release  : 4
URL      : https://repo1.maven.org/maven2/sslext/sslext/1.2-0/sslext-1.2-0.jar
Source0  : https://repo1.maven.org/maven2/sslext/sslext/1.2-0/sslext-1.2-0.jar
Source1  : https://repo1.maven.org/maven2/sslext/sslext/1.2-0/sslext-1.2-0.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-1.1
Requires: mvn-sslext-data = %{version}-%{release}

%description
No detailed description available

%package data
Summary: data components for the mvn-sslext package.
Group: Data

%description data
data components for the mvn-sslext package.


%prep

%build

%install
mkdir -p %{buildroot}/usr/share/java/.m2/repository/sslext/sslext/1.2-0
cp %{SOURCE0} %{buildroot}/usr/share/java/.m2/repository/sslext/sslext/1.2-0

mkdir -p %{buildroot}/usr/share/java/.m2/repository/sslext/sslext/1.2-0
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/sslext/sslext/1.2-0


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/sslext/sslext/1.2-0/sslext-1.2-0.jar
/usr/share/java/.m2/repository/sslext/sslext/1.2-0/sslext-1.2-0.pom
